[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "feed race erode still horn pet blade also toe blanket glance cricket own brand cover unusual before goddess purchase dentist mountain estate dust equal"
